version: 2

defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/python:3.6-jessie-node-browsers

filter_only_master: &filter_only_master
  filters:
    branches:
      only: master

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: ~/app
          paths:
            - ./*

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: yarn generate
      - persist_to_workspace:
          root: ~/app
          paths:
            - ./*

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: sudo pip install awscli
      - run: aws s3 sync ./dist/ s3://blog.houga.cc --exact-timestamps --delete --exclude "*.html" --cache-control max-age=31536000
      - run: aws s3 sync ./dist/ s3://blog.houga.cc --exact-timestamps --delete --exclude "*" --include "*.html" --cache-control no-store
      - run: aws cloudfront create-invalidation --distribution-id $CF_DIST_ID --paths "/*"

workflows:
  version: 2
  build-deploy:
    jobs:
      - install
      - build:
          requires:
            - install
      - deploy:
          <<: *filter_only_master
          requires:
            - build
